In [ ]:
# 변수 선언 및 초기화
a = 10  # 정수형 변수
b = 3.14  # 실수형 변수
c = "Hello, World!"  # 문자열 변수
d = True  # 불리언 변수

# 데이터 타입 확인
print(type(a))  # <class 'int'>
print(type(b))  # <class 'float'>
print(type(c))  # <class 'str'>
print(type(d))  # <class 'bool'>

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [ ]:
# 리스트 (List)
my_list = [1, 2, 3, 4, 5]  # 리스트 선언
print(my_list[0])  # 리스트의 첫 번째 요소 출력

# 튜플 (Tuple)
my_tuple = (1, 2, 3, 4, 5)  # 튜플 선언
print(my_tuple[0])  # 튜플의 첫 번째 요소 출력

# 딕셔너리 (Dictionary)
my_dict = {"name": "Alice", "age": 25}  # 딕셔너리 선언
print(my_dict["name"])  # 딕셔너리의 'name' 키에 해당하는 값 출력

1
1
Alice


In [ ]:
# 함수 정의
def greet(name):
    return f"Hello, {name}!"

# 함수 호출
print(greet("Alice"))  # "Hello, Alice!" 출력

# 모듈 사용 (예: math 모듈)
import math
print(math.sqrt(16))  # math 모듈의 sqrt 함수 사용, 4.0 출력

Hello, Alice!
4.0


In [ ]:
'''
넘파이(Numpy)
넘파이(Numpy)는 파이썬에서 과학 계산을 위한 핵심 라이브러리로, 다차원 배열 객체와 다양한 수학 함수들을 제공합니다.
'''

# 넘파이 임포트
import numpy as np

# 넘파이 배열 생성
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # [1 2 3 4 5] 출력

[1 2 3 4 5]


In [ ]:
# 1차원 배열 생성
arr1 = np.array([1, 2, 3])

# 2차원 배열 생성
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# 배열 초기화
zeros = np.zeros((2, 3))  # 2x3 배열을 0으로 초기화
ones = np.ones((2, 3))  # 2x3 배열을 1로 초기화


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # 배열의 형태 출력, (2, 3)
print(arr.dtype)  # 배열의 데이터 타입 출력, int64


(2, 3)
int64


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])  # 첫 번째 요소 출력, 1
print(arr[1:3])  # 두 번째부터 세 번째 요소까지 출력, [2 3]


1
[2 3]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # 배열의 요소별 덧셈, [5 7 9]
print(arr1 - arr2)  # 배열의 요소별 뺄셈, [-3 -3 -3]


[5 7 9]
[-3 -3 -3]


In [ ]:
arr = np.array([1, 2, 3])
scalar = 2

print(arr * scalar)  # 배열의 모든 요소에 스칼라 곱셈, [2 4 6]


[2 4 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sqrt(arr))  # 배열의 모든 요소에 대해 제곱근 계산, [1. 1.41421356 1.73205081 2. 2.23606798]


[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

reshaped = np.reshape(arr, (3, 2))  # 배열 형태 변경, [[1 2] [3 4] [5 6]]
flattened = arr.flatten()  # 배열을 1차원으로 평탄화, [1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concatenated = np.concatenate((arr1, arr2))  # 배열 결합, [1 2 3 4 5 6]
split = np.split(concatenated, 2)  # 배열 분할, [array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
arr = np.array([3, 1, 2])

sorted_arr = np.sort(arr)  # 배열 정렬, [1 2 3]
index = np.where(arr == 2)  # 값이 2인 요소의 인덱스 검색, (array([2]),)


In [ ]:
matrix = np.array([[1, 2], [3, 4]])

# 행렬 곱셈
product = np.dot(matrix, matrix)  # [[7 10] [15 22]]

# 역행렬
inverse = np.linalg.inv(matrix)  # [[-2.  1.] [ 1.5 -0.5]]


In [ ]:
random_arr = np.random.rand(3, 2)  # 3x2 배열에 난수 생성
print(random_arr)

[[0.65041309 0.11013645]
 [0.94545011 0.84259681]
 [0.36445637 0.91025797]]


In [ ]:
'''
판다스(Pandas)

판다스(Pandas)는 데이터 조작 및 분석을 위한 파이썬 라이브러리로, 특히 데이터프레임(DataFrame)이라는 강력한 데이터 구조를 제공합니다.
이를 통해 데이터 분석, 정리, 변환, 시각화 등을 쉽게 수행할 수 있습니다.
'''

'\n판다스(Pandas)\n\n판다스(Pandas)는 데이터 조작 및 분석을 위한 파이썬 라이브러리로, 특히 데이터프레임(DataFrame)이라는 강력한 데이터 구조를 제공합니다. \n이를 통해 데이터 분석, 정리, 변환, 시각화 등을 쉽게 수행할 수 있습니다.\n'

In [ ]:
# 판다스 임포트
import pandas as pd

# 간단한 데이터프레임 생성
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)  # 데이터프레임 출력

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [ ]:
# 시리즈 생성
s = pd.Series([1, 2, 3, 4, 5])
print(s)  # 시리즈 출력

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
# 데이터프레임 생성
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)  # 데이터프레임 출력

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [ ]:
'''

# CSV 파일 읽기
df = pd.read_csv('data.csv')
print(df)  # CSV 파일의 내용을 데이터프레임으로 출력

# CSV 파일 쓰기
df.to_csv('output.csv', index=False)  # 데이터프레임을 CSV 파일로 저장

'''

"\n\n# CSV 파일 읽기\ndf = pd.read_csv('data.csv')\nprint(df)  # CSV 파일의 내용을 데이터프레임으로 출력\n\n# CSV 파일 쓰기\ndf.to_csv('output.csv', index=False)  # 데이터프레임을 CSV 파일로 저장\n\n"

In [ ]:
'''

# Excel 파일 읽기
df = pd.read_excel('data.xlsx')
print(df)  # Excel 파일의 내용을 데이터프레임으로 출력

# Excel 파일 쓰기
df.to_excel('output.xlsx', index=False)  # 데이터프레임을 Excel 파일로 저장

'''


"\n\n# Excel 파일 읽기\ndf = pd.read_excel('data.xlsx')\nprint(df)  # Excel 파일의 내용을 데이터프레임으로 출력\n\n# Excel 파일 쓰기\ndf.to_excel('output.xlsx', index=False)  # 데이터프레임을 Excel 파일로 저장\n\n"

In [ ]:
'''

import sqlite3

# SQLite 데이터베이스 연결
conn = sqlite3.connect('database.db')

# SQL 쿼리를 통해 데이터 읽기
df = pd.read_sql_query('SELECT * FROM table_name', conn)
print(df)  # SQL 쿼리 결과를 데이터프레임으로 출력

# 데이터프레임을 SQL 테이블로 저장
df.to_sql('table_name', conn, if_exists='replace', index=False)

'''


"\n\nimport sqlite3\n\n# SQLite 데이터베이스 연결\nconn = sqlite3.connect('database.db')\n\n# SQL 쿼리를 통해 데이터 읽기\ndf = pd.read_sql_query('SELECT * FROM table_name', conn)\nprint(df)  # SQL 쿼리 결과를 데이터프레임으로 출력\n\n# 데이터프레임을 SQL 테이블로 저장\ndf.to_sql('table_name', conn, if_exists='replace', index=False)\n\n"

In [ ]:
# 특정 열 선택
print(df['Name'])  # 'Name' 열 출력

# 조건에 따른 행 필터링
filtered_df = df[df['Age'] > 30]
print(filtered_df)  # 'Age'가 30보다 큰 행들 출력


0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
      Name  Age
2  Charlie   35


In [ ]:
# 데이터 정렬
sorted_df = df.sort_values(by='Age')
print(sorted_df)  # 'Age' 기준으로 정렬된 데이터프레임 출력

# 데이터 요약
print(df.describe())  # 데이터프레임의 요약 통계 출력


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0


In [ ]:
# 결측치 확인
print(df.isnull().sum())  # 각 열의 결측치 개수 출력

# 결측치 채우기
df['Age'].fillna(df['Age'].mean(), inplace=True)  # 'Age' 열의 결측치를 평균값으로 채움


Name    0
Age     0
dtype: int64


In [ ]:
# 데이터프레임 병합
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
merged_df = pd.concat([df1, df2])
print(merged_df)  # 두 데이터프레임을 병합하여 출력

# 데이터프레임 결합
df1 = pd.DataFrame({'key': ['A', 'B'], 'value': [1, 2]})
df2 = pd.DataFrame({'key': ['A', 'B'], 'value': [3, 4]})
joined_df = pd.merge(df1, df2, on='key')
print(joined_df)  # 두 데이터프레임을 'key' 열을 기준으로 결합하여 출력


   A  B
0  1  3
1  2  4
0  5  7
1  6  8
  key  value_x  value_y
0   A        1        3
1   B        2        4


In [ ]:
'''
피벗 테이블은 특정 열(‘Age’)에 대해 집계 연산을 수행하고, 결과를 재구성하여 새로운 테이블을 생성합니다.

그룹화는 여러 열(‘Age’, ‘Score’)에 대해 집계 연산을 수행하고, 각 그룹의 평균값을 계산하여 결과를 반환합니다.
'''

import pandas as pd

# 예제 데이터프레임 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35, 28, 32, 36],
    'Score': [85, 90, 95, 88, 92, 98]
}
df = pd.DataFrame(data)

# 피벗 테이블 생성
pivot_table = df.pivot_table(values='Age', index='Name', aggfunc='mean')
print(pivot_table)  # 'Name'을 기준으로 'Age'의 평균값을 계산하여 피벗 테이블 생성

          Age
Name         
Alice    26.5
Bob      31.0
Charlie  35.5


In [ ]:
# 그룹화
grouped_df = df.groupby('Name').mean()
print(grouped_df)  # 'Name'을 기준으로 그룹화하여 각 그룹의 평균값 계산

          Age  Score
Name                
Alice    26.5   86.5
Bob      31.0   91.0
Charlie  35.5   96.5
